# Bachelor Thesis

© 2026 Yvan Richard   
University of St. Gallen, Spring Term 2026

## Observations of WRDS TAQ derived data

The data sample runs from June, 1st 2018 to August, 13 2020

---

In [1]:
# load libs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# load data
df_main = pd.read_csv("../../data/taq/taq.csv")

/var/folders/7v/_v_y1jpx0rl056gg5rkjsw4r0000gn/T/ipykernel_33113/4244936262.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_main = pd.read_csv("../../data/taq/taq.csv")

In [4]:
df_main.head()

,DATE,SYM_ROOT,SYM_SUFFIX,BuyNumTrades_LR,SellNumTrades_LR,total_trade,BuyVol_LR,SellVol_LR,total_vol,symbol,...,BuyVol_Retail,buy_dv_Retail,SellNumTrades_Retail,SellVol_Retail,sell_dv_Retail,total_trade_retail,total_vol_retail,total_dv_retail,avg_buy_price_Retail,bs_ratio_retail_vol
0,2018-04-02,A,NaN,13321.0,13960.0,27281.0,1400583.0,1311493.0,2712076.0,A,...,31602.0,2.046686e+06,460.0,30905.0,1.992981e+06,744.0,62507.0,4.039667e+06,64.828002,0.011151
1,2018-04-02,AA,NaN,9279.0,10267.0,19546.0,999782.0,1004852.0,2004634.0,AA,...,87829.0,3.927226e+06,494.0,102569.0,4.588325e+06,848.0,190398.0,8.515551e+06,44.588851,0.077417
2,2018-04-02,AABA,NaN,20367.0,22658.0,43025.0,2732007.0,2948505.0,5680512.0,AABA,...,115701.0,8.308914e+06,230.0,146710.0,1.054286e+07,705.0,262411.0,1.885178e+07,71.783488,0.118170
3,2018-04-02,AAC,NaN,297.0,360.0,657.0,25464.0,41396.0,66860.0,AAC,...,1435.0,1.609869e+04,6.0,219.0,2.476022e+03,10.0,1654.0,1.857471e+04,11.203150,0.735187
4,2018-04-02,AADR,NaN,60.0,50.0,110.0,7351.0,8953.0,16304.0,AADR,...,2577.0,1.483895e+05,26.0,2738.0,1.573159e+05,43.0,5315.0,3.057053e+05,57.619806,0.030292

In [5]:
# number of unique symbols
print(df_main["symbol"].nunique())

11435

In [6]:
# intersection of unique symbols in TAQ data and unique tickers in Barber et al. (2022)
with open("../../data/replication/unique_tickers_main_pseudo.txt", "r") as f:
    unique_tickers_main = set(line.strip() for line in f)

unique_symbols_taq = set(df_main["symbol"].unique())
overlap_symbols = unique_tickers_main.intersection(unique_symbols_taq)
print(f"Number of unique tickers in Barber et al. (2022) main data: {len(unique_tickers_main)}")
print(f"Number of unique symbols in TAQ data: {len(unique_symbols_taq)}")
print(f"Number of overlapping unique symbols: {len(overlap_symbols)}")

Number of unique tickers in Barber et al. (2022) main data: 8447
Number of unique symbols in TAQ data: 11435
Number of overlapping unique symbols: 8129

In [10]:
# missing values in TAQ data
reports = df_main.isna().sum()
for column, count in reports.items():
    print(f"Column '{column}' has {count} missing values.")

Column 'DATE' has 0 missing values.
Column 'SYM_ROOT' has 0 missing values.
Column 'SYM_SUFFIX' has 4698878 missing values.
Column 'BuyNumTrades_LR' has 58312 missing values.
Column 'SellNumTrades_LR' has 58312 missing values.
Column 'total_trade' has 58312 missing values.
Column 'BuyVol_LR' has 58312 missing values.
Column 'SellVol_LR' has 58312 missing values.
Column 'total_vol' has 58312 missing values.
Column 'symbol' has 0 missing values.
Column 'CPrc' has 41168 missing values.
Column 'OPrc' has 28226 missing values.
Column 'ret_mkt_m' has 45089 missing values.
Column 'BuyNumTrades_tick' has 118684 missing values.
Column 'BuyVol_tick' has 118684 missing values.
Column 'buy_dv_tick' has 118684 missing values.
Column 'SellNumTrades_tick' has 118684 missing values.
Column 'SellVol_tick' has 118684 missing values.
Column 'sell_dv_tick' has 118684 missing values.
Column 'total_trade_tick' has 118684 missing values.
Column 'BuyNumTrades_wrds' has 10392 missing values.
Column 'SellNumTrades_wrds' has 10392 missing values.
Column 'bs_ratio_num' has 58312 missing values.
Column 'bs_ratio_vol' has 58313 missing values.
Column 'BuyNumTrades_Retail' has 362587 missing values.
Column 'BuyVol_Retail' has 362587 missing values.
Column 'buy_dv_Retail' has 362587 missing values.
Column 'SellNumTrades_Retail' has 362587 missing values.
Column 'SellVol_Retail' has 362587 missing values.
Column 'sell_dv_Retail' has 362587 missing values.
Column 'total_trade_retail' has 362587 missing values.
Column 'total_vol_retail' has 362587 missing values.
Column 'total_dv_retail' has 362587 missing values.
Column 'avg_buy_price_Retail' has 555659 missing values.
Column 'bs_ratio_retail_vol' has 362587 missing values.

In [11]:
# length of data set
print(f"Number of rows in TAQ data: {len(df_main)}")

Number of rows in TAQ data: 5223510

In [17]:
aapl = df_main[df_main["symbol"] == "AAPL"]

aapl.head()

,DATE,SYM_ROOT,SYM_SUFFIX,BuyNumTrades_LR,SellNumTrades_LR,total_trade,BuyVol_LR,SellVol_LR,total_vol,symbol,...,BuyVol_Retail,buy_dv_Retail,SellNumTrades_Retail,SellVol_Retail,sell_dv_Retail,total_trade_retail,total_vol_retail,total_dv_retail,avg_buy_price_Retail,bs_ratio_retail_vol
12,2018-04-02,AAPL,NaN,124657.0,162856.0,287513.0,15304403.0,18561016.0,33865419.0,AAPL,...,2197346.0,3.654305e+08,11270.0,2128631.0,3.540337e+08,22360.0,4325977.0,7.194642e+08,166.206233,0.015884
8320,2018-04-03,AAPL,NaN,96156.0,109183.0,205339.0,13088062.0,14029954.0,27118016.0,AAPL,...,1981676.0,3.304902e+08,8540.0,1947677.0,3.248827e+08,17300.0,3929353.0,6.553729e+08,166.716581,0.008653
16628,2018-04-04,AAPL,NaN,108545.0,126826.0,235371.0,14599407.0,17045271.0,31644678.0,AAPL,...,2168433.0,3.665496e+08,9788.0,2028491.0,3.427701e+08,18895.0,4196924.0,7.093197e+08,168.976869,0.033344
24891,2018-04-05,AAPL,NaN,87651.0,97908.0,185559.0,11671504.0,12239476.0,23910980.0,AAPL,...,1714444.0,2.971029e+08,8368.0,1670868.0,2.895514e+08,15957.0,3385312.0,5.866543e+08,173.319302,0.012872
33150,2018-04-06,AAPL,NaN,111636.0,136310.0,247946.0,13887228.0,16379760.0,30266988.0,AAPL,...,2096115.0,3.566391e+08,8843.0,2001677.0,3.406926e+08,18467.0,4097792.0,6.973317e+08,170.034174,0.023046

In [19]:
aapl.tail()

,DATE,SYM_ROOT,SYM_SUFFIX,BuyNumTrades_LR,SellNumTrades_LR,total_trade,BuyVol_LR,SellVol_LR,total_vol,symbol,...,BuyVol_Retail,buy_dv_Retail,SellNumTrades_Retail,SellVol_Retail,sell_dv_Retail,total_trade_retail,total_vol_retail,total_dv_retail,avg_buy_price_Retail,bs_ratio_retail_vol
3757329,2020-08-25,AAPL,NaN,376406.0,350246.0,726652.0,24496688.0,24771031.0,49267719.0,AAPL,...,4682377.0,2.324297e+09,52554.0,4835598.0,2.400132e+09,130645.0,9517975.0,4.724429e+09,496.265475,0.016098
3757330,2020-08-26,AAPL,NaN,314911.0,282868.0,597779.0,19068533.0,18562995.0,37631528.0,AAPL,...,3470014.0,1.749594e+09,44614.0,3763278.0,1.897371e+09,111802.0,7233292.0,3.646965e+09,504.074286,0.040544
3757331,2020-08-27,AAPL,NaN,320533.0,324110.0,644643.0,17498784.0,18698519.0,36197303.0,AAPL,...,2969664.0,1.493303e+09,47114.0,2988662.0,1.502710e+09,115874.0,5958326.0,2.996013e+09,502.692003,0.003188
3757332,2020-08-28,AAPL,NaN,343989.0,306298.0,650287.0,18785364.0,19299308.0,38084672.0,AAPL,...,3284102.0,1.647696e+09,43844.0,3216383.0,1.613741e+09,120486.0,6500485.0,3.261437e+09,501.605611,0.010418
3757333,2020-08-31,AAPL,NaN,1559663.0,1001257.0,2560920.0,105767591.0,91323549.0,197091140.0,AAPL,...,23668795.0,3.057179e+09,185700.0,20029584.0,2.587174e+09,639728.0,43698379.0,5.644353e+09,129.167372,0.083280