# Bachelor Thesis

© 2026 Yvan Richard   
University of St. Gallen, Spring Term 2026

## Observations of Processed Robintrack Data (2018-2020)

---

In [63]:
# load libraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [64]:
# load data
df = pd.read_csv("../../data/processed/robintrack/robintrack_merged.csv")

Once the data are loaded into memory, the goal is to reproduce the summary statistics of Barber et al. (2022).

In [65]:
# convert date to datetime format
df["date"] = pd.to_datetime(df["date"], format="%Y-%m-%d")

# int for users_close and users_last
df["users_close"] = df["users_close"].astype("Int64")
df["users_last"] = df["users_last"].astype("Int64")

Once we have pre-processed our data, we drop the NA values (the Robinhood app was down during three distinct periods over the sample).

In [66]:
# drop all rows with missing values
df = df.dropna()

# summary statistics of users_close and users_last
df[["users_close", "users_last"]].describe().T

,count,mean,std,min,25%,50%,75%,max
users_close,5686630.0,2085.046765,15542.717124,0.0,35.0,162.0,681.0,990622.0
users_last,5686630.0,2085.976997,15549.993242,0.0,35.0,162.0,681.0,990622.0

In [67]:
df.head()

        date  users_close  users_last ticker
0 2018-06-01           70          70    RIV
1 2018-06-02           70          70    RIV
2 2018-06-03           70          70    RIV
3 2018-06-04           70          70    RIV
4 2018-06-05           70          70    RIV

In [68]:
# number of unique tickers
df["ticker"].nunique()

8593

In [75]:
# compare unique tickers here with the unique tickers in main data of Barber et al. (2022)
with open("../../data/replication/unique_tickers_main_pseudo.txt", "r") as f:
    unique_tickers_main = set(line.strip() for line in f)

unique_tickers_rh = set(df["ticker"].unique())
overlap_tickers = unique_tickers_main.intersection(unique_tickers_rh)
print(f"Number of unique tickers in Barber et al. (2022) main data: {len(unique_tickers_main)}")
print(f"Number of unique tickers in Robintrack data: {len(unique_tickers_rh)}")
print(f"Number of overlapping unique tickers: {len(overlap_tickers)}")

Number of unique tickers in Barber et al. (2022) main data: 8447
Number of unique tickers in Robintrack data: 8593
Number of overlapping unique tickers: 8443

In [69]:
# length of the data frame
len(df)

5686630

In [70]:
# summary statistics
df.describe().T

,count,mean,min,25%,50%,75%,max,std
date,5686630,2019-07-29 20:48:34.889417216,2018-06-01 00:00:00,2019-01-12 00:00:00,2019-08-10 00:00:00,2020-02-19 00:00:00,2020-08-13 00:00:00,NaN
users_close,5686630.0,2085.046765,0.0,35.0,162.0,681.0,990622.0,15542.717124
users_last,5686630.0,2085.976997,0.0,35.0,162.0,681.0,990622.0,15549.993242

In [71]:
# users_close = 990622.0
df[df['users_close'] == 990622.0]

              date  users_close  users_last ticker
3451638 2020-05-09       990622      990622    ACB

In [76]:
# filter with overlap tickers
df_overlap = df.copy()
df_overlap = df_overlap[df_overlap["ticker"].isin(overlap_tickers)]

# summary statistics of users_close and users_last for the overlapping tickers
df_overlap[["users_close", "users_last"]].describe().T

,count,mean,std,min,25%,50%,75%,max
users_close,5676665.0,2086.611874,15555.308776,0.0,35.0,162.0,681.0,990622.0
users_last,5676665.0,2087.541539,15562.589012,0.0,35.0,162.0,681.0,990622.0