# Bachelor Thesis

© 2026 Yvan Richard   
University of St. Gallen, Spring Term 2026

## Observations of Processed Robintrack Data (2018-2020)

---

In [21]:
# load libraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [44]:
# load data
df = pd.read_csv("../../data/processed/robintrack/robintrack_merged.csv")

Once the data are loaded into memory, the goal is to reproduce the summary statistics of Barber et al. (2022).

In [45]:
# convert date to datetime format
df["date"] = pd.to_datetime(df["date"], format="%Y-%m-%d")

# int for users_close and users_last
df["users_close"] = df["users_close"].astype("Int64")
df["users_last"] = df["users_last"].astype("Int64")

Once we have pre-processed our data, we drop the NA values (the Robinhood app was down during three distinct periods over the sample).

In [46]:
# drop all rows with missing values
df = df.dropna()

# summary statistics of users_close and users_last
df[["users_close", "users_last"]].describe().T

,count,mean,std,min,25%,50%,75%,max
users_close,5686630.0,2085.046765,15542.717124,0.0,35.0,162.0,681.0,990622.0
users_last,5686630.0,2085.976997,15549.993242,0.0,35.0,162.0,681.0,990622.0

In [47]:
df.head()

        date  users_close  users_last ticker
0 2018-06-01           70          70    RIV
1 2018-06-02           70          70    RIV
2 2018-06-03           70          70    RIV
3 2018-06-04           70          70    RIV
4 2018-06-05           70          70    RIV

In [48]:
# number of unique tickers
df["ticker"].nunique()

8593

In [49]:
# length of the data frame
len(df)

5686630