# Bachelor Thesis

© 2026 Yvan Richard   
University of St. Gallen, Spring Term 2026

## Observations of Interim CRSP Data

The data sample runs from June 1, 2018 to August 31, 2020

---

In this notebook, I explore the CRSP data once I applied the first cleaning steps contained in [this pipeline](../../src/CRSP_cleaning.py).

In [28]:
# load libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Once the libraries are loaded, I proceed with loading the data.

In [29]:
# load the data CRSP_18_20.csv
df = pd.read_csv("../../data/interim/CRSP_cleaned_a.csv")

Once the data are loaded, I conduct a basic inspection.

In [30]:
# number of unique tickers
df["ticker"].nunique()

9007

In [31]:
# length of the data frame
len(df)

4431138

In [32]:
# na values
df.isna().sum()

permno    0
date      0
ret       0
prc       0
vol       0
shrout    0
ticker    0
exchcd    0
dtype: int64

The data set is therefore clean.

In [33]:
df.head()

   permno        date       ret        prc       vol   shrout ticker  exchcd
0   10026  2018-05-01 -0.038862  132.07001  102619.0  18702.0   JJSF     3.0
1   10026  2018-05-02 -0.018248  129.66000   74013.0  18702.0   JJSF     3.0
2   10026  2018-05-03 -0.006478  128.82001   60755.0  18702.0   JJSF     3.0
3   10026  2018-05-04  0.030119  132.70000   55396.0  18702.0   JJSF     3.0
4   10026  2018-05-07  0.017709  135.05000   95096.0  18702.0   JJSF     3.0

We can also build the `size` variable for the market capitalization.

In [34]:
df["size"] = df["prc"].abs() * df["shrout"] * 1000

In [37]:
df.tail(20)

,permno,date,ret,prc,vol,shrout,ticker,exchcd,size
4431118,93436,2020-08-04,0.001347,1487.00000,8389296.0,186362.0,TSLA,3.0,2.771203e+11
4431119,93436,2020-08-05,-0.001332,1485.02002,4967584.0,186362.0,TSLA,3.0,2.767513e+11
4431120,93436,2020-08-06,0.003071,1489.57996,5961375.0,186362.0,TSLA,3.0,2.776011e+11
4431121,93436,2020-08-07,-0.024752,1452.70996,8872984.0,186362.0,TSLA,3.0,2.707299e+11
4431122,93436,2020-08-10,-0.023501,1418.56995,7512738.0,186362.0,TSLA,3.0,2.643675e+11
4431123,93436,2020-08-11,-0.031144,1374.39001,8607394.0,186362.0,TSLA,3.0,2.561341e+11
4431124,93436,2020-08-12,0.131236,1554.76001,21828364.0,186362.0,TSLA,3.0,2.897482e+11
4431125,93436,2020-08-13,0.042605,1621.00000,20387865.0,186362.0,TSLA,3.0,3.020928e+11
4431126,93436,2020-08-14,0.018328,1650.70996,12562182.0,186362.0,TSLA,3.0,3.076296e+11
4431127,93436,2020-08-17,0.112031,1835.64001,20145252.0,186362.0,TSLA,3.0,3.420935e+11
4431128,93436,2020-08-18,0.028028,1887.08997,16436978.0,186362.0,TSLA,3.0,3.516819e+11
4431129,93436,2020-08-19,-0.004536,1878.53003,12178422.0,186362.0,TSLA,3.0,3.500866e+11
4431130,93436,2020-08-20,0.065636,2001.82996,20557219.0,186362.0,TSLA,3.0,3.730650e+11
4431131,93436,2020-08-21,0.024053,2049.97998,21415137.0,186362.0,TSLA,3.0,3.820384e+11
4431132,93436,2020-08-24,-0.017454,2014.19995,19982162.0,186362.0,TSLA,3.0,3.753703e+11
4431133,93436,2020-08-25,0.004538,2023.33997,10628719.0,186362.0,TSLA,3.0,3.770737e+11
4431134,93436,2020-08-26,0.064166,2153.16992,14184847.0,186362.0,TSLA,3.0,4.012691e+11
4431135,93436,2020-08-27,0.039746,2238.75000,23593610.0,186362.0,TSLA,3.0,4.172179e+11
4431136,93436,2020-08-28,-0.011323,2213.39990,20038951.0,186362.0,TSLA,3.0,4.124936e+11
4431137,93436,2020-08-31,0.125689,498.32001,118162555.0,931809.0,TSLA,3.0,4.643391e+11